accounts/urls.py
"""Create the URL paths for accounts."""

from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    # Include the default authorization URLs.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

learning_logs/urls.py
"""Define the URLs for the Learning Logs app."""

from django.urls import path

from . import views

app_name = "learning_logs"
urlpatterns = [
    # The website home page.
    path("", views.index, name="index"),
    # Topics page.
    path("topics/", views.topics, name="topics"),
    # Page for an individual topic.
    path("topics/<int:topic_id>/", views.topic, name="topic"),
    # Page to add a topic.
    path("new_topic/", views.new_topic, name="new_topic"),
    # Page to add an entry.
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),
    # Page to edit an entry.
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Models for the Learning Logs app.

class Topic(models.Model):
    """A topic that the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Print the text stored in the class."""
        return self.text


class Entry(models.Model):
    """Specific details about a topic."""
    # Cascade deletion to prevent unlinked data.
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Metadata for entries."""
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a shortened version of the entry's name."""
        if len(str(self.text)) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != "POST":
        # Create a blank form.
        form = UserCreationForm()
    else:
        # Submit completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and redirect to the home page.
            login(request, new_user)
            return redirect("learning_logs:index")

    # Display the form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_logs/views.py
from tabnanny import check

from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def check_topic_owner(topic, request):
    if topic.owner != request.user:
        raise Http404


# Create your views here.
def index(request):
    """Render the home page for the Learning Logs website."""
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """Show all the topics for the Learning Logs website."""
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """Show a topic and all of its entries."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic to the list."""
    if request.method != "POST":
        # If there isn't data, create a new topic.
        form = TopicForm()
    else:
        # Process the data submitted.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    # Display the form if it is blank or invalid.
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry to a topic."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    if request.method != "POST":
        # If there isn't data, create a new topic.
        form = EntryForm()
    else:
        # Process the data submitted.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.topic = topic
            entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)

    # Display the form if it is blank or invalid.
    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != "POST":
        # Fill the form with the current entry by default.
        form = EntryForm(instance=entry)
    else:
        # Process the data submitted.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial_scale=1">
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- Main links -->
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              Topics
            </a>
          </li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}!</span>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
            </li>
          {% endif %}
        </ul> <!-- End of account links -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Log Out
            </button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible sections of navbar -->

    </div> <!-- Closes navbar container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h1>{{ topic }}</h1>
{% endblock page_header %}

{% block content %}
  <h4>Edit Entry</h4>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-outline-dark" href="{% url 'learning_logs:topic' topic.id %}">
      Back
    </a>
    {% bootstrap_button button_type="submit" content="Save Changes" %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Track your learning.</h1>

      <p class="lead">Make your own Learning Log and keep notes on the topics
      you're learning about. Whenever you learn something new about a topic,
      make an entry to summarize what you've learned.</p>

      <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">
        Register &raquo;
      </a>
    </div>
  </div>
{% endblock page_header %}

{% block content %}
<p>
    Learning Log is an app to help you keep track of your learning. You can
    add information about any topic!
</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h1>{{ topic }}</h1>
{% endblock page_header %}

{% block content %}
  <h4>Add Entry</h4>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a class="btn btn-outline-dark" href="{% url 'learning_logs:topic' topic.id %}">
      Back
    </a>
    {% bootstrap_button button_type="submit" content="Add Entry" %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h1>Add a Topic</h1>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add Topic" %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}
  <h4>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add an entry</a>
  </h4>
  {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:"M d, Y H:i T" }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          Edit Entry
        </a></small>
      </h4>
      <!-- Card body and text -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}
        </a>
      </li>
    {% empty %}
      <li class="list-grou-item border-0">No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a New Topic</a>

{% endblock content %}